# This file was generated by GoReleaser. DO NOT EDIT.
cask "matter-cli" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "f81e252176465755cbdab70401ecedc8ae24e66f68941ae52a8e14349aa7e25c"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5bbfad508891bd0e30e0cf4d153838fdddb6cda9a19c1202c7db637ccf6144b7"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a211b91d509d0bb79d654a94e2570a6823841fa714d1e2dce0581e32a8986188"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ffa276c5e95562762ce9db3d91a58d24536bf2ec47b72e0b65486b664b6e760e"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_amd64.tar.gz"
    end
  end

  name "matter-cli"
  desc "Matter protocol CLI controller — commission and control Matter devices from your terminal"
  homepage "https://github.com/p0fi/matter-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matter"]
    end
  end

  # No zap stanza required
end
