# This file was generated by GoReleaser. DO NOT EDIT.
cask "matter-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "694e743c5fcddf75c87029c0c2819bef3161616fe80b0afbc9a18b32bc47f1ab"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcdff7671613e68e677d34c07ed854978e0890de5a1ed6c5e82dcdca079ae87b"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37e383f63dbd466665e7f7efba7ed6bf1f3c8458c218c5bc13d99c93624941a7"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd88258d50bd40480afc8975795c8a3bfdea278d1346dc8d46fc709a0c19b87b"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_arm64.tar.gz"
    end
  end

  name "matter-cli"
  desc "Matter protocol CLI controller — commission and control Matter devices from your terminal"
  homepage "https://github.com/p0fi/matter-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matter"]
    end
  end

  # No zap stanza required

end
