# This file was generated by GoReleaser. DO NOT EDIT.
cask "matter-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "bb9ae853424f021251444f6bac3135d767fe79383bd1527aba3c33ced63c63f1"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "868f57e98d044a8d635b45e5014d8979659cabbc1ab85aebea32b7c94c33da7e"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a59889d0173fb4d11140b8382868f14311fee9bdb120e37838b01b9e18129aa"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48c33214d8cdacabdd7f72ee666f8a8e4668451a02ef44de05381b55eb350966"
      url "https://github.com/p0fi/matter-cli/releases/download/v#{version}/matter_linux_arm64.tar.gz"
    end
  end

  name "matter-cli"
  desc "Matter protocol CLI controller — commission and control Matter devices from your terminal"
  homepage "https://github.com/p0fi/matter-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "matter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/matter"]
    end
  end

  # No zap stanza required

end
